// <auto-generated />
using ECCUSBET_Web.Models.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECCUSBET_Web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_ECCUSBET.Core.Entities.BetEntity", b =>
                {
                    b.Property<int>("IdDimensionamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ComprimentoBet")
                        .HasColumnType("float");

                    b.Property<int>("IdOrcamento")
                        .HasColumnType("int");

                    b.Property<double>("LarguradaBet")
                        .HasColumnType("float");

                    b.Property<double>("ProfundidadeM")
                        .HasColumnType("float");

                    b.Property<string>("TipodeOcupacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VolUtio")
                        .HasColumnType("float");

                    b.HasKey("IdDimensionamento");

                    b.ToTable("Tabela de Dimensionamento");
                });

            modelBuilder.Entity("ECCUSBET_Web.Models.Entities.OrcamentoEntity", b =>
                {
                    b.Property<int>("IdOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDimensionamento")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Servico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrcamento");

                    b.HasIndex("IdDimensionamento")
                        .IsUnique();

                    b.ToTable("Tabela de Orçamento");
                });

            modelBuilder.Entity("ECCUSBET_Web.Models.Entities.OrcamentoEntity", b =>
                {
                    b.HasOne("API_ECCUSBET.Core.Entities.BetEntity", "Dimensionamento")
                        .WithOne("Orcamento")
                        .HasForeignKey("ECCUSBET_Web.Models.Entities.OrcamentoEntity", "IdDimensionamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensionamento");
                });

            modelBuilder.Entity("API_ECCUSBET.Core.Entities.BetEntity", b =>
                {
                    b.Navigation("Orcamento");
                });
#pragma warning restore 612, 618
        }
    }
}
